#端口号
server:
  port: 8082
 
spring:
  redis:  #redis信息指定
    host: 192.168.159.132
    port: 6379
    password: 123123
swagger:
 SMS_PLATFORM_CACHE_TITLE: 短信平台缓存服务API列表
 CONTACT_NAME: 马大侠
 CONTACT_URL: http://www.baidu.com
 CONTACT_EMAIL: 3034624344@qq.com
 CACHE_DESCRIPTION: 这个是缓存
 LICENSEURL:
 VERSION: v1.0.0
 BASEPACKAGE: com.mg.smsplatform.cache.controller #扫描的包
